### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by lepture** [jessuni/typlog-aoyama#1]
![theme-aoyama typlog io_](https://user-images.githubusercontent.com/290496/161020006-9346a398-5429-4547-9923-5bf17453c36f.png)
![theme-aoyama typlog io_ (1)](https://user-images.githubusercontent.com/290496/161020023-cf1c3b5f-95f2-48b9-bb63-63c3ed0fad15.png)

failed to take full size screenshot

**Comment by jessuni** [comment]
How about the landing page?

**Comment by lepture** [comment]
![aoyama](https://user-images.githubusercontent.com/290496/161203111-d93435a0-c69d-4ed2-a810-f39f3550353e.jpg)

**Comment by jessuni** [comment]
![dark mode motion](https://user-images.githubusercontent.com/41285428/168568931-89273359-1c2b-448b-aae9-8155ca1b6631.png)
![light mode motion](https://user-images.githubusercontent.com/41285428/168569283-632044e9-cfb2-4fe9-bfb4-d4fe80c9ca99.png)

**Comment by jessuni** [comment]
Featured posts cover:
![horizontal](https://user-images.githubusercontent.com/41285428/168575596-f78d7985-a3fe-438e-a637-e4efa28bc48f.png)
![vertical](https://user-images.githubusercontent.com/41285428/168575684-72b134fa-bdff-4630-a965-4b2d38003bb5.png)
